2023-08-14 14:16:48,815 ERROR: Exception on /course [GET] [in C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\main\routes.py", line 208, in courses
    course_list = courses.query.all()
AttributeError: 'function' object has no attribute 'query'
2023-08-14 14:33:38,356 INFO: Certi Tech startup [in C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\__init__.py:71]
2023-08-14 14:33:40,625 ERROR: Exception on / [GET] [in C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\main\routes.py", line 16, in index
    return render_template('index.html',  title='Home')
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\base.html", line 64, in block 'navbar'
    {% block footer %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\base.html", line 83, in block 'footer'
    <a href="{{ url_for('main.Corporate_sponsor') }}">Corporate Sponsor</a>
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.Corporate_sponsor'. Did you mean 'main.corporate_sponsor' instead?
2023-08-14 14:34:28,359 INFO: Certi Tech startup [in C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\__init__.py:71]
2023-08-14 14:34:31,472 ERROR: Exception on / [GET] [in C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\main\routes.py", line 16, in index
    return render_template('index.html',  title='Home')
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\index.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\base.html", line 64, in block 'navbar'
    {% block footer %}
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\templates\base.html", line 83, in block 'footer'
    <a href="{{ url_for('main.Corporate_sponsor') }}">Corporate Sponsor</a>
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.Corporate_sponsor'. Did you mean 'main.corporate_sponsor' instead?
2023-08-14 14:36:48,993 INFO: Certi Tech startup [in C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\__init__.py:71]
2023-08-14 14:36:57,762 ERROR: Exception on /course [GET] [in C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\Eliza Lenjani\Desktop\2205FlaskNew\app\main\routes.py", line 213, in courses
    course_list = courses.query.all()
AttributeError: 'function' object has no attribute 'query'
