2023-08-10 13:13:49,666 ERROR: Exception on /jobs [GET] [in C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\main\routes.py", line 149, in jobs
    return render_template('jobs.html', title='Jobs', job_listings=job_listings)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\jobs.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\base.html", line 103, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\jobs.html", line 6, in block 'app_content'
    <a href="{{ url_for('main.create_job', id=-1)}}">Add New Article</a>
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.create_job' with values ['id']. Did you mean 'main.create_jobs' instead?
2023-08-10 13:13:58,397 ERROR: Exception on /jobs [GET] [in C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py:1414]
Traceback (most recent call last):
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 2190, in wsgi_app
    response = self.full_dispatch_request()
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1486, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\main\routes.py", line 149, in jobs
    return render_template('jobs.html', title='Jobs', job_listings=job_listings)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\templating.py", line 151, in render_template
    return _render(app, template, context)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\templating.py", line 132, in _render
    rv = template.render(context)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\jinja2\environment.py", line 1301, in render
    self.environment.handle_exception()
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\jinja2\environment.py", line 936, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\jobs.html", line 1, in top-level template code
    {% extends "base.html" %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\base.html", line 1, in top-level template code
    {% extends "bootstrap/base.html" %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 23, in block 'body'
    {% block content -%}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\base.html", line 103, in block 'content'
    {% block app_content %}{% endblock %}
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\templates\jobs.html", line 6, in block 'app_content'
    <a href="{{ url_for('main.create_jobs', id=-1)}}">Add New Article</a>
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1697, in url_for
    return self.handle_url_build_error(error, endpoint, values)
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\flask\app.py", line 1686, in url_for
    rv = url_adapter.build(  # type: ignore[union-attr]
  File "C:\Users\jai_s\Desktop\2205Flask\2205Flask\venv\lib\site-packages\werkzeug\routing\map.py", line 950, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.exceptions.BuildError: Could not build url for endpoint 'main.create_job' with values ['id']. Did you mean 'main.create_jobs' instead?
2023-08-10 13:14:01,684 INFO: Certi Tech startup [in C:\Users\jai_s\Desktop\2205Flask\2205Flask\app\__init__.py:71]
